micronaut:
  application:
    name: grpc

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/grpc
    driverClassName: org.postgresql.Driver
    username: user
    password: pass
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
