micronaut:
  application:
    name: grpc

grpc:
  server:
    port: ${GRPC_PORT:50051}

datasources:
  default:
    url: ${DATABASE_URL:`jdbc:postgresql://localhost:5432/grpc`}
    driverClassName: ${DATABASE_DRIVER:org.postgresql.Driver}
    username: ${DATABASE_USER:user}
    password: ${DATABASE_PASSWORD:pass}
    schema-generate: ${DATABASE_GENERATE:CREATE_DROP}
    dialect: ${DATABASE_DIABLECT:POSTGRES}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: ${JPA_STRATEGY:update}
