version: '3.8'

services:

  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    network_mode: host
    env_file:
      - postgres.env

  pgadmin:
    image: dpage/pgadmin4
    network_mode: host
    container_name: pgadmin
    env_file:
      - pgadmin.env
    ports:
      - 5433:5433